linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - unused

run:
  timeout: 5m
  concurrency: 4
  tests: true

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - tmp
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

# Default is 3 lines of context, which is often insufficient
output:
  sort-results: true

# Settings for specific linters
linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: "github.com/theblitlabs/parity-runner"