global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "parity-protocol"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/metrics"

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
    metrics_path: "/metrics"
    honor_labels: true

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    metrics_path: "/metrics"
