server:
  port:
  host:
  endpoint:
  websocket:
    write_wait:
    pong_wait:
    max_message_size:

ethereum:
  rpc:
  chain_id:
  token_address:
  stake_wallet_address:

runner:
  server_url:
  webhook_port:
  docker:
    memory_limit:
    cpu_limit:
    timeout:
