server:
  port:
  host:
  endpoint:
  websocket:
    ping_interval:
    write_wait:
    pong_wait:
    max_message_size:

database:
  host:
  port:
  user:
  password:
  name:
  sslmode:
  max_open_conns:
  max_idle_conns:
  conn_max_lifetime:
  url:

ethereum:
  rpc:
  chain_id:
  token_address:
  stake_wallet_address:

runner:
  server_url:
  websocket_url:
  webhook_port: 8090
  api_prefix:
  docker:
    memory_limit:
    cpu_limit:
    timeout:
  ipfs:
    image: "ipfs/kubo:v0.25.0"
    api_port: 5001
    gateway_port: 8081
    swarm_port: 4001
    data_dir:

ipfs:
  api_url: http://localhost:5001

p2p:
  listen_addrs:
    - "/ip4/0.0.0.0/tcp/9000"
  bootstrap_peers:
    - "/ip4/123.45.67.89/tcp/9000/p2p/QmPeerID"
    - "/dns4/bootstrap.example.com/tcp/9000/p2p/QmOtherPeerID"
  subgroup:
    min_size: 3
    max_size: 7
  consensus:
    timeout: 30s
    threshold: 0.67
