name: Build & Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      ipfs:
        image: ipfs/kubo:latest
        ports:
          - 5001:5001
          - 8080:8080
        options: >-
          --health-cmd "ipfs id"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true
      - name: Install dependencies
        run: go mod download
      - name: Wait for IPFS
        run: |
          timeout 30s bash -c 'until curl -s http://localhost:5001/api/v0/id > /dev/null; do sleep 1; done'
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          IPFS_API: http://localhost:5001

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -v ./...
          GOOS=darwin GOARCH=amd64 go build -v ./...
          GOOS=windows GOARCH=amd64 go build -v ./...
