apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_NAME}
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 3600
      postgresVersion: 1500
      timescaledb: false
    editable: true
    version: 1
